<?php

add_action( 'wp_enqueue_scripts', 'load_vue_script' );
function load_vue_script() {

    // register the Vue build script.
    wp_register_script( // the app build script generated by Webpack.
        'vue_search_app',
        get_stylesheet_directory_uri() . '/dist/assets/js/index.js',
        array(),
        false,
        true
    );

    global $post;
    wp_localize_script(
      'vue_search_app', 
      'wpData', 
      array( 
        'template_directory_uri' => get_stylesheet_directory_uri(), 
        'rest_url' => untrailingslashit( esc_url_raw( rest_url() ) ), 
    ));

    wp_enqueue_script( 'vue_search_app' );
      
}

add_action( 'wp_enqueue_scripts', 'load_vue_style' );
function load_vue_style() {
    wp_enqueue_style(
        'vue-spa-wordpress-css',
        get_stylesheet_directory_uri() . '/dist/assets/css/index.css',
        null,
        filemtime( get_stylesheet_directory() . '/dist/assets/css/index.css' )
    );
    

}